In [50]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
ds = pd.read_csv('ttw2_finalSpell.csv')

In [ ]:
##########




In [52]:
print(ds.shape)

(31962, 3)


In [53]:
#ds.replace(np.nan, " ")
ds=ds.fillna("")

In [54]:
ds.head

<bound method NDFrame.head of           id  label                                              tweet
0          1      0  user father dysfunctional selfish drags kids d...
1          2      0  user user thanks credit cant use cause dont of...
2          3      0                                   birthday majesty
3          4      0                        model love u take u time ur
4          5      0                                 factsguide society
...      ...    ...                                                ...
31957  31958      0                                  ate user is youtu
31958  31959      0  see nina turner airwaves trying wrap mantle ge...
31959  31960      0    listening sad songs monday morning ots work sad
31960  31961      1                       user vandalised condemns act
31961  31962      0                                  thank user follow

[31962 rows x 3 columns]>

In [55]:
ds['tweet']

0        user father dysfunctional selfish drags kids d...
1        user user thanks credit cant use cause dont of...
2                                         birthday majesty
3                              model love u take u time ur
4                                       factsguide society
                               ...                        
31957                                    ate user is youtu
31958    see nina turner airwaves trying wrap mantle ge...
31959      listening sad songs monday morning ots work sad
31960                         user vandalised condemns act
31961                                    thank user follow
Name: tweet, Length: 31962, dtype: object

In [56]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1,1), min_df=0, stop_words='english')
print(tf)

TfidfVectorizer(min_df=0, stop_words='english')


In [57]:
ds["tweet"][1118]

''

In [65]:
tfidf_matrix = tf.fit_transform(ds['tweet'][:1000])

In [66]:
print(tfidf_matrix.shape)

(1000, 2472)


In [69]:
print(type(tfidf_matrix))

<class 'scipy.sparse.csr.csr_matrix'>


In [68]:
print(tfidf_matrix)

  (0, 639)	0.42858532205657873
  (0, 1171)	0.3874144707392011
  (0, 619)	0.42858532205657873
  (0, 1911)	0.4045019179131466
  (0, 640)	0.42858532205657873
  (0, 751)	0.3462436194218234
  (0, 2301)	0.1238848151675673
  (1, 1718)	0.3568405491248768
  (1, 2317)	0.3568405491248768
  (1, 2397)	0.3568405491248768
  (1, 1508)	0.3225616589343904
  (1, 610)	0.22999358237020404
  (1, 335)	0.3568405491248768
  (1, 2298)	0.2772474309300277
  (1, 482)	0.3568405491248768
  (1, 2182)	0.29488642821642913
  (1, 2301)	0.20629323123106247
  (2, 1318)	0.8238507574178815
  (2, 216)	0.5668067832180408
  (3, 2295)	0.520945945087961
  (3, 2212)	0.4744761540549123
  (3, 1291)	0.43734289538182436
  (3, 1407)	0.5587655084100241
  (4, 2009)	0.7071067811865475
  (4, 731)	0.7071067811865475
  :	:
  (993, 111)	0.5307504831499021
  (993, 2301)	0.1697198490796319
  (994, 1020)	0.5773502691896257
  (994, 1019)	0.5773502691896257
  (994, 551)	0.5773502691896257
  (995, 1668)	0.7947274806272733
  (995, 1765)	0.6069664171

In [70]:
print(tfidf_matrix.shape)

(1000, 2472)


In [71]:
print(tf.vocabulary_)

{'user': 2301, 'father': 751, 'dysfunctional': 640, 'selfish': 1911, 'drags': 619, 'kids': 1171, 'dysfunction': 639, 'thanks': 2182, 'credit': 482, 'use': 2298, 'cause': 335, 'dont': 610, 'offer': 1508, 'wheelchair': 2397, 'vans': 2317, 'px': 1718, 'birthday': 216, 'majesty': 1318, 'model': 1407, 'love': 1291, 'time': 2212, 'ur': 2295, 'factsguide': 731, 'society': 2009, 'huge': 1049, 'fan': 741, 'fare': 746, 'big': 205, 'talking': 2142, 'leave': 1222, 'chaos': 352, 'pay': 1575, 'disputes': 593, 'camping': 311, 'tomorrow': 2219, 'danny': 522, 'school': 1890, 'year': 2449, 'exams': 708, 'think': 2195, 'land': 1198, 'welcome': 2387, 'im': 1075, 'consumer': 448, 'price': 1675, 'index': 1095, 'mom': 1411, 'climbed': 398, 'previous': 1673, 'daddy': 512, 'today': 2215, 'calls': 307, 'middle': 1385, 'build': 289, 'wall': 2352, 'chant': 351, 'comment': 421, 'ouchjunior': 1542, 'angrygot': 67, 'thankful': 2181, 'paper': 1562, 'agree': 38, 'smiles': 1999, 'ig': 1068, 'make': 1320, 'people': 1586

In [72]:
cosine_similarities = linear_kernel(tfidf_matrix)

print("shape :",cosine_similarities.shape)

shape : (1000, 1000)


In [73]:
print(cosine_similarities)

[[1.         0.0255566  0.         ... 0.12388482 0.         0.01481253]
 [0.0255566  1.         0.         ... 0.20629323 0.         0.02466585]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.12388482 0.20629323 0.         ... 1.         0.         0.11956696]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.01481253 0.02466585 0.         ... 0.11956696 0.         1.        ]]


In [82]:
print(cosine_similarities[2][2])

1.0


In [76]:
print(type(cosine_similarities[0][1]))

<class 'numpy.float64'>
